### ISSUE TITLE
Social information problem in Safari (-category)

### ISSUE THREAD

**Issue by lottebijlsma** [lottebijlsma/lottebijlsma.github.io#36]
![Safari Category Problem](https://scontent-bru2-1.xx.fbcdn.net/v/t34.0-12/14593592_10209292602464929_853189058_n.png?oh=97729c5fd4fb73534c57af878d13fdd9&oe=57F6E911)

Should be: -category.

**Comment by thibmaek** [comment]
You could try:
```scss
.social-info {
  …
  h3 {
    …
    &::before {content: '—';}
  }
  …
}
```

> You might need to add padding/margin in the before pseudoselector.
