### ISSUE TITLE
Refactor code in main.scss

### ISSUE THREAD

**Issue by thibmaek** [lottebijlsma/lottebijlsma.github.io#40]
> This makes no sense in [main.scss](https://github.com/lottebijlsma/lottebijlsma.github.io/blob/master/css/main.scss#L131-L145)

There is a lot of duplicate code due to these repeated media queries that do the same thing.
I suggest only using the media query mixin where you need to change the value other than the others, for those that contain the same rules just create an inline media query that sets the range for min/max width and put code there once.

When the current code is converted from scss to css the Sass parser will output css code like this:
```css
@media (max-width: 330px) {
  font-size: 2.2rem;
  padding-left: 1rem;
}
@media (min-width: 331px) and (max-width: 666px) {
  font-size: 2.2rem;
  padding-left: 1.2rem;
}
@media (min-width: 667px) and (max-width: 736px) {
  font-size: 2.2rem;
  padding-left: 1.2rem;
}
@media (min-width: 737px) and (max-width: 958px) {
  font-size: 2.2rem;
  padding-left: 1.2rem;
}
```
where an inline media query would make it more performant & reduces code like such:
```css
@media (max-width: 330px) {
  font-size: 2.2rem;
  padding-left: 1rem;
}
@media (min-width: 331px) and (max-width: 958px) {
  font-size: 2.2rem;
  padding-left: 1.2rem;
}
```

Please make this a top priority to fix @lottebijlsma
