### ISSUE TITLE
CSS should be prefixed through build pipeline

### ISSUE THREAD

**Issue by thibmaek** [lottebijlsma/lottebijlsma.github.io#7]
Add `jekyll-assets` and `autoprefixer` to the dependencies and update _config.yml:

```yml
assets:
   autoprefixer:
      - "last 2 versions"
      - "ie > 9"
```
